### ISSUE TITLE
Game binary

### ISSUE THREAD

**Issue by 1337331** [darfink/mutool-rs#1]
Do you have the 1.02d binary now?
I have been looking for it for a long time anyway

Any help is greatly appreciated

**Comment by darfink** [comment]
I scoured the internet in an attempt to find it, but had no luck.

However, I did find a 1.04b client, if that is of any interest.

I'd also be interested in the 1.02d binary if it's available somewhere.

**Comment by 1337331** [comment]
Thank you but no.

 I have 1.02Q and I just wanted to steal your offset to save my time lmao.

It really makes people lament that time has made files disappear on the Internet.

**Comment by whoamiamiwhohaha** [comment]
hi people... seems like fate brought us all together here lol, after 6 years all at once
